# Generated by Django 6.0.4 on 2026-06-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('home_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField()),
                ('plaque', models.CharField(blank=True, max_length=20, null=True)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('national_code', models.CharField(blank=True, max_length=10, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('profile_image', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
