# Generated by Django 6.0.4 on 2026-06-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_verificationcode_alter_order_total_amount_int'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_fa', models.CharField(max_length=200)),
                ('category_en', models.CharField(max_length=100, unique=True)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
